src/SportsForEveryone.WebUI/Models/ActivityTypeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SportsForEveryone.WebUI.Models
{
    public class ActivityTypeViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
    }
}

src/SportsForEveryone.WebUI/Models/ClubCreationViewModel.cs
namespace SportsForEveryone.WebUI.Models
{
    public class ClubCreationViewModel
    {
        public int ClubId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string WebSite { get; set; }
        public IFormFile Picture { get; set; }
    }
}

src/SportsForEveryone.WebUI/Models/ClubViewModel.cs
namespace SportsForEveryone.WebUI.Models
{
    public class ClubViewModel
    {
        public int ClubId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string WebSite { get; set; }
        public string Picture { get; set; }
    }
}

src/SportsForEveryone.WebUI/Models/ErrorViewModel.cs
namespace SportsForEveryone.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/SportsForEveryone.WebUI/Controllers/ActivityController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportsForEveryone.WebUI.Controllers
{
    public class ActivityController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SportsForEveryone.WebUI/Controllers/ActivityTypeController.cs
using Microsoft.AspNetCore.Mvc;
using SportsForEveryone.Application.DTOs;
using SportsForEveryone.Application.Interfaces;
using SportsForEveryone.WebUI.Models;

namespace SportsForEveryone.WebUI.Controllers
{
    public class ActivityTypeController : Controller
    {
        public readonly IActivityTypeService _activityTypeService; 

        public ActivityTypeController(IActivityTypeService activityTypeService)
        {
            _activityTypeService = activityTypeService;
        }

        public IActionResult Index()
        {
            var act = _activityTypeService.GetAll();
            var list = new List<ActivityTypeViewModel>();
            foreach (var item in act)
            {
                list.Add(new ActivityTypeViewModel { 
                    Id =  item.ActivityTypeId,
                    Name = item.Name
                });
            }            
            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ActivityTypeViewModel activityTypeViewModel)
        {
            _activityTypeService.Create(new ActivityTypeCreationDTO { Name = activityTypeViewModel.Name });
            return RedirectToAction("Index");
        }
    }
}

src/SportsForEveryone.WebUI/Controllers/AdministratorController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportsForEveryone.WebUI.Controllers
{
    public class AdministratorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SportsForEveryone.WebUI/Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using SportsForEveryone.Application.DTOs;
using SportsForEveryone.Application.Interfaces;
using SportsForEveryone.WebUI.Models;

namespace SportsForEveryone.WebUI.Controllers
{
    public class ClubController : Controller
    {
        private readonly IClubService _clubService;

        public ClubController(IClubService clubService)
        {
            _clubService = clubService;
        }

        public IActionResult Index()
        {
            var clubs = _clubService.GetAll();
            var clubsModel = new List<ClubViewModel>();
            foreach (var club in clubs)
            {
                clubsModel.Add(new ClubViewModel
                {
                    Name = club.Name,
                    Address = club.Address,
                    ClubId = club.ClubId,
                    Picture = Url.Content(club.Picture),
                    WebSite = club.WebSite,
                });
            }
            return View(clubsModel);
        }



        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create([FromForm] ClubCreationViewModel clubViewModel) 
        {
            _clubService.CreateClub(new ClubCreationDTO
            {
                Name = clubViewModel.Name,
                Address = clubViewModel.Address,
                Picture = clubViewModel.Picture,
                WebSite = clubViewModel.WebSite,
            });
            return RedirectToAction("Index");
        } 
    }
}

src/SportsForEveryone.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SportsForEveryone.Application.DTOs;
using SportsForEveryone.Application.Interfaces;
using SportsForEveryone.Infrastructure;
using SportsForEveryone.WebUI.Models;
using System.Diagnostics;

namespace SportsForEveryone.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;;
        }

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SportsForEveryone.WebUI/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportsForEveryone.WebUI.Controllers
{
    public class PostController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SportsForEveryone.WebUI/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportsForEveryone.WebUI.Controllers
{
    public class ReviewController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SportsForEveryone.WebUI/Controllers/TrainerController.cs
using Microsoft.AspNetCore.Mvc;

namespace SportsForEveryone.WebUI.Controllers
{
    public class TrainerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SportsForEveryone.WebUI/Views/ActivityType/Create.cshtml
@model ActivityTypeViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Activity Type</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>       
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/SportsForEveryone.WebUI/Views/ActivityType/Index.cshtml
@model List<ActivityTypeViewModel>
@{
    ViewData["Title"] = "Activity Type Page";
}


<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    @foreach (var act in Model)
    {
        <div>@act.Name</div>
    }
</div>
<p>
    <a asp-action="Create">Create New</a>
</p>

src/SportsForEveryone.WebUI/Views/Club/ClubPartialView.cshtml
@model ClubViewModel

<div class="text-center">
    <h1 class="display-4">Hello</h1>
    <h1 class="display-4">@Model.Name</h1>
    <p><a href=@Model.WebSite></a></p>
    <h1 class="display-4">@Model.Address</h1>
    <img src=@Model.Picture alt="clubs"></img>

</div>

src/SportsForEveryone.WebUI/Views/Club/Create.cshtml
@model ClubCreationViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal" enctype="multipart/form-data">
        <h4>Club</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger" enctype="multipart/form-data"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="WebSite" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="WebSite" class="form-control" />
                <span asp-validation-for="WebSite" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group" >
            <label asp-for="Picture" class="col-md-2 control-label">Input picture</label>
            <div class="form-group">
                <input type="file" class="form-control" asp-for="Picture" />
                @Html.TextBoxFor(m => m.Picture, new { type = "file"})
                <span asp-validation-for="Picture"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/SportsForEveryone.WebUI/Views/Club/Index.cshtml
@model List<ClubViewModel>
@{
    ViewData["Title"] = "Club Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
</div>
<div>
    @foreach(var club in Model)
    {
        @Html.PartialAsync("ClubPartialView", club).Result
    }   
</div>
<p>
    <a asp-action="Create">Create New</a>
</p>

src/SportsForEveryone.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    
</div>

src/SportsForEveryone.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sports For Everyone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SportsForEveryone.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SportsForEveryone.WebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ActivityType" asp-action="Index">Activity Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Club" asp-action="Index">Clubs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SportsForEveryone.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>